spring.application.name=taskit

spring.datasource.url=jdbc:postgresql://localhost:5432/taskit
spring.datasource.username=taskit
spring.datasource.password=taskit

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.profiles.active=dev

server.servlet.context-path=/api/v1

taskit.jwt.secret=${TASKIT_JWT_SECRET:change-me-please-change-me-please-change-me-please}
taskit.jwt.access-token-minutes=15
taskit.jwt.refresh-token-days=7

taskit.cors.allowed-origin=${TASKIT_CORS_ALLOWED_ORIGIN:http://localhost:5173}